- Overview.html
- Overview.src.html
This is using https://github.com/w3c/screen-orientation/pull/90
> Allow requestFullscreen() to be called from an orientation change event (closes #34)

- Overview.html
- Overview.src.html
These are changes that make (some) sense even with anolis, done first
to make the Bikeshed changes smaller:
* Add ids to headings
* Don't quote attributes without whitespace
* &oslash; → ø
Part of #47.
> Prepare for conversion to Bikeshed

- fullscreen.bs
- fullscreen.html
The definitions used to use document as argument to fullscreen or
unfullscreen an element, but document could be induced from the
element's node document.
> To fullscreen/unfullscreen, do not take document as an argument

- fullscreen.bs
- fullscreen.html
Spec discussion at https://github.com/w3c/webcomponents/issues/180.
The rough consensus was:
https://github.com/w3c/webcomponents/issues/180#issuecomment-224244250
This resolves #42
> Update fullscreen spec to be Shadow DOM compliant

- fullscreen.bs
- fullscreen.html
If the document becomes inactive after the request, then there will not
be another animation frame task, in which case the promise will be left
hanging instead.
Fixes #67.
> Reject exitFullscreen() in inactive documents

- fullscreen.bs
While reviewing #65, I noticed two issues in the current algorithm:
1. If the current document has more than a single fullscreen element, its browsering context container will be accidentally unfullscreened because in algorithm of "exit fullscreen", "doc" is added to "exitDocs" if "doc" has more than a single fullscreen element, and in that case, the document of the browsing context container of "doc" will be added to "exitDocs" in the next step.
2. A browsing context container can be unfullscreened accidentally by its child document even if its "iframe fullscreen flag" is set, because the steps in "exit fullscreen" doesn't check it.
This pull request changes the algorithm to collecting all documents which we are going to call "unfullscreen an element" on.
*** …
> Change algorithm of "collect documents to unfullscreen"

- fullscreen.bs
Bikeshed complained that "[SVG] is replaced by [SVG11]."
Keep using [SVG] with no number, like for [CSS].
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/svg-ref/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/40c8947...c81af9d.html)
> Fix Bikeshed error about SVG reference

- fullscreen.bs
This also clarifies the description of top layer order somewhat.
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/usa-infra/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/48fdc4d...5077749.html)
> Meta: use infra for lists and sets

- fullscreen.bs
https://dom.spec.whatwg.org/#concept-node-remove-ext uses removedNode
and an optional oldParent, which isn't used by Fullscreen.
Drive-by: drop unnecessary "run these substeps"
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/removing-steps/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/50efe97...625d044.html)
> Editorial: update variable name in removing steps

- fullscreen.bs
Given that there is an "unfullscreen a document" operation, this
algorithm can easily be assumed to be the set of documents for which
that should be called, i.e., that all of the documents returned will
exit fully.
At the beginning of the animation frame task there's no guarantee that
doc still has a fullscreen element, but later in "unfullscreen exitDoc's
fullscreen element" it is assumed to have one. Fix this with an early
return.
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/collect-documents-to-unfullscreen/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/c8164af...ae151d8.html)
> Clarify what "collect documents to unfullscreen" returns

- fullscreen.bs
The implementation in Blink uses continue here, which would matter if
one of the ancestor documents had a fullscreen element other than the
iframe containing the document now requesting fullscreen.
Perhaps this should be continue, but that would be a separate change.
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/infra-break/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/0a4787a...15e285f.html)
> Editorial: use Infra's break to clarify requestFullscreen() iteration

- fullscreen.bs
This appears to be needed per
https://bugzilla.mozilla.org/show_bug.cgi?id=1364025.
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/annevk/unscopable/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/946d3ec...5e8528d.html)
> Add [Unscopable] to Document.prototype.fullscreen

- fullscreen.bs
Test: https://github.com/w3c/web-platform-tests/pull/5901
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/request-fully-active/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/3513c94...b1b684a.html)
> Require that the document is fully active in requestFullscreen()

- fullscreen.bs
Fixes https://github.com/whatwg/fullscreen/issues/33.
Drive-by: capitalization in lt attributes to match dfn.
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/pending-element-moved/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/d1d1b4a...e96e446.html)
> In requestFullscreen(), handle the pending element moving

- fullscreen.bs
This means that changes to document.fullscreenElement and other state
will be observable as soon as the resize itself is (e.g. via
window.innerWidth) and before resize or scroll events are fired.
The fullscreenchange event is still delayed to animation frame timing.
This also includes a slight change when /resize/ is true in "exit
fullscreen". By changing /doc/ to /topLevelDoc/ in this case, we can
make sure that we always fully unfullscreen all documents in this case.
This makes a "fully exit fullscreen" corner case unnecessary.
Fixes https://github.com/whatwg/fullscreen/issues/74.
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/fullscreen-asap/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/aaa10c1...a62b790.html)
> Fullscreen/unfullscreen ASAP; fire events at animation frame timing

- fullscreen.bs
As discussed in https://github.com/whatwg/html/pull/2763.
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/run-the-fullscreen-steps/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/4208e5a...6ec12c5.html)
> Editorial: rename "run the fullscreen rendering steps" and add note

- fullscreen.bs
This way, interactions between the algorithms for fullscreen and
dialog are simplified. Example concern:
https://github.com/whatwg/fullscreen/pull/102#issuecomment-332039536
This also makes it easier to reinstate hierarchy restrictions:
https://github.com/whatwg/fullscreen/pull/91
Tests: https://chromium-review.googlesource.com/c/chromium/src/+/684435
***
[Preview](https://fullscreen.spec.whatwg.org/branch-snapshots/disallow-dialog/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/fullscreen/10649f2...70e0801.html)
> Disallow dialog.requestFullscreen()

- fullscreen.bs
Mistake in https://github.com/whatwg/fullscreen/pull/94.
***
<a href="https://whatpr.org/fullscreen/117.html" title="Last updated on Jan 29, 2018, 8:40 AM GMT (a8564e5)">Preview</a> | <a href="https://whatpr.org/fullscreen/117/eac5263...a8564e5.html" title="Last updated on Jan 29, 2018, 8:40 AM GMT (a8564e5)">Diff</a>
> Editorial: remove a stray/double "tree order" in note

- fullscreen.bs
Oversight in https://github.com/whatwg/fullscreen/pull/94.
***
<a href="https://whatpr.org/fullscreen/118.html" title="Last updated on Jan 29, 2018, 8:51 AM GMT (0d5c71b)">Preview</a> | <a href="https://whatpr.org/fullscreen/118/2d7f7f0...0d5c71b.html" title="Last updated on Jan 29, 2018, 8:51 AM GMT (0d5c71b)">Diff</a>
> Editorial: fix grammar in notes about run the fullscreen steps

- fullscreen.bs
If the fullscreen element is not connected anymore dispatch
event and unfullscreen the element right away.
This allows an element that is being removed to see that it isn't the
fullscreen element synchronously.
***
<a href="https://whatpr.org/fullscreen-1/128.html" title="Last updated on Aug 22, 2018, 8:40 PM GMT (349d042)">Preview</a> | <a href="https://whatpr.org/fullscreen/128/05c072b...349d042.html" title="Last updated on Aug 22, 2018, 8:40 PM GMT (349d042)">Diff</a>
> Remove from top layer synchronously for not connected elements

- fullscreen.bs
Add an attribute of the FullscreenOptions dictionary that hints
at whether a navigation bar is preferred or not.
***
<a href="https://whatpr.org/fullscreen-1/129.html" title="Last updated on Sep 7, 2018, 7:12 PM GMT (af61df4)">Preview</a> | <a href="https://whatpr.org/fullscreen/129/06c6e07...af61df4.html" title="Last updated on Sep 7, 2018, 7:12 PM GMT (af61df4)">Diff</a>
> Add FullscreenOptions dictionary to requestFullscreen

- fullscreen.bs
Closes: #144
***
<a href="https://whatpr.org/fullscreen/145.html" title="Last updated on Feb 22, 2019, 3:02 AM UTC (23899b4)">Preview</a> | <a href="https://whatpr.org/fullscreen/145/7ecd709...23899b4.html" title="Last updated on Feb 22, 2019, 3:02 AM UTC (23899b4)">Diff</a>
> Fix logical error of filling fullscreenElements (3.12)

- fullscreen.bs
Closes https://github.com/whatwg/fullscreen/pull/157.
***
<a href="https://whatpr.org/fullscreen/158.html" title="Last updated on Sep 25, 2019, 9:28 PM UTC (570fe8f)">Preview</a> | <a href="https://whatpr.org/fullscreen/158/2a9e7a5...570fe8f.html" title="Last updated on Sep 25, 2019, 9:28 PM UTC (570fe8f)">Diff</a>
> Add empty dictionary default value for requestFullscreen

- fullscreen.bs
The output fullscreen.html is exactly the same before and after this
change.
Was part of https://github.com/whatwg/fullscreen/pull/157.
***
<a href="https://whatpr.org/fullscreen/159.html" title="Last updated on Sep 26, 2019, 9:24 AM UTC (456da35)">Preview</a> | <a href="https://whatpr.org/fullscreen/159/20ea24b...456da35.html" title="Last updated on Sep 26, 2019, 9:24 AM UTC (456da35)">Diff</a>
> Meta: remove <dfn> markup that has no effect on output

- fullscreen.bs
Fixes https://github.com/whatwg/fullscreen/issues/160.
***
<a href="https://whatpr.org/fullscreen/163.html" title="Last updated on Jan 29, 2020, 11:43 AM UTC (ac928e1)">Preview</a> | <a href="https://whatpr.org/fullscreen/163/69482d3...ac928e1.html" title="Last updated on Jan 29, 2020, 11:43 AM UTC (ac928e1)">Diff</a>
> Editorial: use "transient activation" instead of obsolete concept

- fullscreen.bs
This is to enable the scoping/highlighting of variables, and revealed
one mistaken use of "top layer" as a variable.
***
<a href="https://whatpr.org/fullscreen/174.html" title="Last updated on Jun 11, 2020, 3:31 PM UTC (bc45f57)">Preview</a> | <a href="https://whatpr.org/fullscreen/174/b1cfc66...bc45f57.html" title="Last updated on Jun 11, 2020, 3:31 PM UTC (bc45f57)">Diff</a>
> Meta: wrap algorithms in <div algorithm>

- fullscreen.bs
Follows https://github.com/w3c/webappsec-feature-policy/pull/379.
***
<a href="https://whatpr.org/fullscreen/178.html" title="Last updated on Jun 29, 2020, 1:43 PM UTC (fe6acc6)">Preview</a> | <a href="https://whatpr.org/fullscreen/178/8415b76...fe6acc6.html" title="Last updated on Jun 29, 2020, 1:43 PM UTC (fe6acc6)">Diff</a>
> Link to `Permissions-Policy` header after renaming

- fullscreen.bs
The spec URL and its entry in Specref has not changed, so there it
remains "feature" instead of "permissions".
***
<a href="https://whatpr.org/fullscreen/181.html" title="Last updated on Jul 20, 2020, 10:28 AM UTC (afcb0d2)">Preview</a> | <a href="https://whatpr.org/fullscreen/181/1f4ed06...afcb0d2.html" title="Last updated on Jul 20, 2020, 10:28 AM UTC (afcb0d2)">Diff</a>
> Meta: adapt to the in-progress Permissions Policy renaming

- fullscreen.bs
* Adds appropriate `<dfn>`s and references for navigationUI and its values
* Adds appropriate `<dfn>`s and references for fullscreenchange and fullscreenerror
* Fixes the for="" value for onfullscreenchange and onfullscreenerror to include both Document and Element, so that now the IDL block for Element links to the correct place.
(Depends on #194.)
***
<a href="https://whatpr.org/fullscreen/195.html" title="Last updated on Jul 19, 2021, 4:28 PM UTC (39ef865)">Preview</a> | <a href="https://whatpr.org/fullscreen/195/3d0e592...39ef865.html" title="Last updated on Jul 19, 2021, 4:28 PM UTC (39ef865)">Diff</a>
> Meta: add/update some definitions

- fullscreen.bs
***
<a href="https://whatpr.org/fullscreen/200.html" title="Last updated on Jan 17, 2022, 5:56 PM UTC (ebc88fe)">Preview</a> | <a href="https://whatpr.org/fullscreen/200/4d9fcf0...ebc88fe.html" title="Last updated on Jan 17, 2022, 5:56 PM UTC (ebc88fe)">Diff</a>
> Editorial: pairs are tuples now

- fullscreen.bs
Follows https://github.com/whatwg/html/pull/6315.
This depends on https://github.com/whatwg/html/pull/8460 and won't build until that lands and is propagated.
***
<a href="https://whatpr.org/fullscreen/208.html" title="Last updated on Nov 2, 2022, 2:45 AM UTC (107797b)">Preview</a> | <a href="https://whatpr.org/fullscreen/208/38e9b40...107797b.html" title="Last updated on Nov 2, 2022, 2:45 AM UTC (107797b)">Diff</a>
> Update to use navigables instead of browsing contexts

- fullscreen.bs
Closes #202
* Interested in WebKit (and bug filed)
* Implemented in Chrome 
* bug filed for Gecko
* http://wpt.live/screen-orientation/fullscreen-interactions.html
* Chromium: already implemented (confirmed on Chrome Android). 
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1798646.
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=247250
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/fullscreen/206.html" title="Last updated on Nov 14, 2022, 5:19 AM UTC (07cd6c6)">Preview</a> | <a href="https://whatpr.org/fullscreen/206/38e9b40...07cd6c6.html" title="Last updated on Nov 14, 2022, 5:19 AM UTC (07cd6c6)">Diff</a>
> Unlock the screen orientation when exiting fullscreen

- fullscreen.bs
Fixes https://github.com/whatwg/fullscreen/issues/201.
* Chromium (proposed by @mfreed7)
* Gecko (@emilio [comment](https://github.com/whatwg/fullscreen/issues/201#issuecomment-1230813781))
* WebKit (@annevk [comment](https://github.com/whatwg/fullscreen/issues/201#issuecomment-1230504035))
* This isn't observable since the computed style is the same both before and after, so no test updates.
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1393369
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1802334
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=248310
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/fullscreen/210.html" title="Last updated on Nov 24, 2022, 4:26 PM UTC …
> Editorial: use inset property in the UA style sheet

- fullscreen.bs
Depends on https://github.com/whatwg/html/pull/3851.
Fixes https://github.com/whatwg/fullscreen/issues/152.
* Chromium: https://github.com/whatwg/fullscreen/pull/153#issuecomment-496521939
* Gecko: https://github.com/whatwg/fullscreen/pull/153#issuecomment-1298746998
* https://github.com/web-platform-tests/wpt/pull/36969
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1804635
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=247920
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/fullscreen/153.html" title="Last updated on May 3, 2023, 7:23 AM UTC (e1ab822)">Preview</a> | <a href="https://whatpr.org/fullscreen/153/a69e295...e1ab822.html" title="Last updated on May 3, 2023, 7:23 AM UTC (e1ab822)">Diff</a>
> Consume user activation in `element.requestFullscreen()`

- fullscreen.bs
This is part of the new popover attribute: https://github.com/whatwg/html/pull/8221
* Chrome
* …
* https://wpt.fyi/results/html/semantics/popovers/popover-top-layer-combinations.html
* https://wpt.fyi/results/html/semantics/popovers/popover-top-layer-interactions.html
* Chromium: Implemented
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1827225
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=255232
***
<a href="https://whatpr.org/fullscreen/204.html" title="Last updated on May 1, 2023, 2:56 PM UTC (4d375fe)">Preview</a> | <a href="https://whatpr.org/fullscreen/204/a69e295...4d375fe.html" title="Last updated on May 1, 2023, 2:56 PM UTC (4d375fe)">Diff</a>
> Hide popovers when making an element fullscreen

- fullscreen.bs
Also reword algos as appropriate.
As far as Fullscreen is concerned, this is *almost* a no-op change, as things are merely moving. The only normative change that's relevant here is in the "fullscreen an element" algo, as it's no longer valid to add something to the top layer when it's already there (see next para for details). At the moment I've changed it to simply check if it's already in the top layer and only add if it's not, but this can be changed as necessary. (There are some other changes to the top-layer handling as it exists in Position 4, but they're in response to CSSWG decisions and are being discussed over there.)
The issue with adding something to the top layer that's already there is that, now that we have multiple things interacting with the top layer, they can have …
> Remove top layer definitions, now that CSS Position 4 contains them.

- fullscreen.bs
Without this patch, the fullscreening an element inside an open popover will make the fullscreen element display:none.
Issue: https://github.com/whatwg/html/issues/9998
Corresponding HTML PR: https://github.com/whatwg/html/pull/10116
* Chrome
* https://bugzilla.mozilla.org/show_bug.cgi?id=1888088
* https://github.com/web-platform-tests/wpt/pull/44146
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1520938
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1888088
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=269928
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/fullscreen/237.html" title="Last updated on May 7, 2024, 2:21 AM UTC (4bd1b11)">Preview</a> | <a …
> Don't close ancestor popovers when fullscreening
